- name: Installing Redis-Server to Master
  hosts: Production[0]
  order: sorted
  serial: 1
  become: yes
  become_method: sudo

  tasks:
 
    - name: Enable Redis-Server & Redis-Sentinel
      shell: apt install -y redis && systemctl enable redis-server && apt install -y redis-sentinel && systemctl enable redis-sentinel

    - name: Installing Redis-Sentinel and Applying New Config
      shell: apt install redis-sentinel

    - name: Start Redis-Sentinel
      shell: systemctl start redis-sentinel
    - name: Enable Redis-Sentinel
      shell: systemctl enable redis-sentinel

    - name: Creating and Changing Ownership for log path of Redis
      shell: mkdir -p /redis/redis_sentinel_data  && mkdir -p /redis/redis_data && mkdir -p /etc/systemd/system/redis.service.d && mkdir -p /etc/systemd/system/sentinel.service.d && mkdir -p /redis/redis_log && chown -R redis:redis /redis/* && chmod 750 /redis/* && chown -R redis:redis /etc/redis/


    - name: Change Redis Server Master Config File
      shell:
        cmd: |
          cat > /etc/redis/redis.conf << EOF
          bind {{ ansible_host }}
          protected-mode yes
          port 6379
          tcp-backlog 511
          timeout 0
          tcp-keepalive 60
          daemonize yes
          supervised systemd
          pidfile "/run/redis/redis-server.pid"
          loglevel notice
          logfile "/redis/redis_log/redis-server.log"
          databases 16
          always-show-logo no
          set-proc-title yes
          proc-title-template "{title} {listen-addr} {server-mode}"
          stop-writes-on-bgsave-error yes
          rdbcompression yes
          rdbchecksum yes
          dbfilename "dump.rdb"
          rdb-del-sync-files no
          dir "/redis/redis_data"
          masterauth {{ ProjectName }}_{{ Year }}_??!

          replica-serve-stale-data yes
          replica-read-only no
          repl-diskless-sync yes
          repl-diskless-sync-delay 5
          repl-diskless-sync-max-replicas 0
          repl-diskless-load disabled
          repl-disable-tcp-nodelay no
          replica-priority 10
          min-replicas-to-write 1
          min-replicas-max-lag 10
          acllog-max-len 128
          requirepass {{ ProjectName }}_{{ Year }}_??!
          lazyfree-lazy-eviction no
          lazyfree-lazy-expire no
          lazyfree-lazy-server-del no
          replica-lazy-flush no
          lazyfree-lazy-user-del no
          lazyfree-lazy-user-flush no
          oom-score-adj no
          oom-score-adj-values 0 200 800
          disable-thp yes
          appendonly yes
          appendfilename "appendonly.aof"
          appenddirname "appendonlydir"
          appendfsync everysec
          no-appendfsync-on-rewrite no
          auto-aof-rewrite-percentage 100
          auto-aof-rewrite-min-size 64mb
          aof-load-truncated yes
          aof-use-rdb-preamble yes
          aof-timestamp-enabled no
          slowlog-log-slower-than 10000
          slowlog-max-len 128
          latency-monitor-threshold 0
          notify-keyspace-events ""
          hash-max-listpack-entries 512
          hash-max-listpack-value 64
          list-max-listpack-size -2
          list-compress-depth 0
          set-max-intset-entries 512
          zset-max-listpack-entries 128
          zset-max-listpack-value 64
          hll-sparse-max-bytes 3000
          stream-node-max-bytes 4kb
          stream-node-max-entries 100
          activerehashing yes
          client-output-buffer-limit normal 0 0 0
          client-output-buffer-limit replica 256mb 64mb 60
          client-output-buffer-limit pubsub 32mb 8mb 60
          hz 10
          dynamic-hz yes
          aof-rewrite-incremental-fsync yes
          rdb-save-incremental-fsync yes
          jemalloc-bg-thread yes
          EOF

    - name: Change Redis Sentinel Master Config File
      shell:
        cmd: |
          cat > /etc/redis/sentinel.conf << EOF
          protected-mode no
          port 26379
          daemonize yes
          supervised systemd
          pidfile "/run/sentinel/redis-sentinel.pid"
          logfile "/redis/redis_log/redis-sentinel.log"
          dir "/redis/redis_sentinel_data"

          sentinel monitor mymaster {{ ansible_host }} 6379 2
          sentinel auth-pass mymaster {{ ProjectName }}_{{ Year }}_??!
          sentinel down-after-milliseconds mymaster 5000
          sentinel failover-timeout mymaster 5000
          sentinel parallel-syncs mymaster 2

          acllog-max-len 128
          sentinel deny-scripts-reconfig yes
          sentinel resolve-hostnames no
          sentinel announce-hostnames no
          EOF

    - name: Change Redis Sentinel Master Config File
      shell:
        cmd: |
          cat > /etc/systemd/system/redis.service.d/override.conf << EOF
          [Service]
          ReadWriteDirectories=/redis/redis_data
          ReadWriteDirectories=/redis/redis_log
          EOF    

    - name: Change Redis Sentinel Master Config File
      shell:
        cmd: |
          cat > /etc/systemd/system/sentinel.service.d/override.conf << EOF
          [Service]
          ReadWriteDirectories=/redis/redis_sentinel_data
          ReadWriteDirectories=/redis/redis_log
          EOF    
    
    - name: Restarting Redis-Server and Applying New Config
      shell: systemctl daemon-reload && systemctl restart redis-server

    - name: Restarting Redis-Sentinel and Applying New Config
      shell: systemctl daemon-reload && systemctl restart redis-sentinel

    - name: Config Cronjob for Redis Log Cleanup
      cron:
        name: "Redis Log Cleaning"
        minute: "08"
        hour: "10"
        job: find /redis/redis_log/ -name "*.log" -type f -mtime +30 -exec rm -rf {} \;
    
    - name: Change Redis-Server Log Rotate
      shell:
         cmd: |
            cat > /etc/logrotate.d/redis-server << EOF
            /redis/redis_log/*.log 
            {
              daily
              missingok
              copytruncate
              rotate 15
              maxage 15
              compress
              notifempty
            }
            EOF

    - name: Restarting Logrotate
      shell: systemctl restart logrotate

- name: Installing Redis-Server to Slave
  hosts: Production[1:3]
  order: sorted
  serial: 1
  become: yes
  become_method: sudo

  tasks:

    - name: Enable Redis-Server & Redis-Sentinel
      shell: apt install -y redis && systemctl enable redis-server && apt install -y redis-sentinel && systemctl enable redis-sentinel

    - name: Creating and Changing Ownership for log path of Redis
      shell: mkdir -p /redis/redis_sentinel_data  && mkdir -p /redis/redis_data && mkdir -p /etc/systemd/system/redis.service.d && mkdir -p /etc/systemd/system/sentinel.service.d && mkdir -p /redis/redis_log && chown -R redis:redis /redis/* && chmod 750 /redis/* && chown -R redis:redis /etc/redis/


    - name: Change Redis Server Slave Config File
      shell:
        cmd: |
          cat > /etc/redis/redis.conf << EOF
          bind {{ ansible_host }}
          protected-mode yes
          port 6379
          tcp-backlog 511
          timeout 0
          tcp-keepalive 60
          daemonize yes
          supervised systemd
          pidfile "/run/redis/redis-server.pid"
          loglevel notice
          logfile "/redis/redis_log/redis-server.log"
          databases 16
          always-show-logo no
          set-proc-title yes
          proc-title-template "{title} {listen-addr} {server-mode}"
          stop-writes-on-bgsave-error yes
          rdbcompression yes
          rdbchecksum yes
          dbfilename "dump.rdb"
          rdb-del-sync-files no
          dir "/redis/redis_data"
          masterauth {{ ProjectName }}_{{ Year }}_??!
          replicaof  {{ Master_Redis_machine_1 }} 6379
          replica-serve-stale-data yes
          replica-read-only no
          repl-diskless-sync yes
          repl-diskless-sync-delay 5
          repl-diskless-sync-max-replicas 0
          repl-diskless-load disabled
          repl-disable-tcp-nodelay no
          replica-priority 30
          min-replicas-to-write 1
          min-replicas-max-lag 10
          acllog-max-len 128
          requirepass {{ ProjectName }}_{{ Year }}_??!
          lazyfree-lazy-eviction no
          lazyfree-lazy-expire no
          lazyfree-lazy-server-del no
          replica-lazy-flush no
          lazyfree-lazy-user-del no
          lazyfree-lazy-user-flush no
          oom-score-adj no
          oom-score-adj-values 0 200 800
          disable-thp yes
          appendonly yes
          appendfilename "appendonly.aof"
          appenddirname "appendonlydir"
          appendfsync everysec
          no-appendfsync-on-rewrite no
          auto-aof-rewrite-percentage 100
          auto-aof-rewrite-min-size 64mb
          aof-load-truncated yes
          aof-use-rdb-preamble yes
          aof-timestamp-enabled no
          slowlog-log-slower-than 10000
          slowlog-max-len 128
          latency-monitor-threshold 0
          notify-keyspace-events ""
          hash-max-listpack-entries 512
          hash-max-listpack-value 64
          list-max-listpack-size -2
          list-compress-depth 0
          set-max-intset-entries 512
          zset-max-listpack-entries 128
          zset-max-listpack-value 64
          hll-sparse-max-bytes 3000
          stream-node-max-bytes 4kb
          stream-node-max-entries 100
          activerehashing yes
          client-output-buffer-limit normal 0 0 0
          client-output-buffer-limit replica 256mb 64mb 60
          client-output-buffer-limit pubsub 32mb 8mb 60
          hz 10
          dynamic-hz yes
          aof-rewrite-incremental-fsync yes
          rdb-save-incremental-fsync yes
          jemalloc-bg-thread yes
          EOF

    - name: Change Redis Sentinel Slave Config File
      shell:
        cmd: |
          cat > /etc/redis/sentinel.conf << EOF
          protected-mode no
          port 26379
          daemonize yes
          supervised systemd
          pidfile "/run/sentinel/redis-sentinel.pid"
          logfile "/redis/redis_log/redis-sentinel.log"
          dir "/redis/redis_sentinel_data"

          sentinel monitor mymaster {{ Master_Redis_machine_1 }} 6379 2
          sentinel auth-pass mymaster {{ ProjectName }}_{{ Year }}_??!
          sentinel down-after-milliseconds mymaster 5000
          sentinel failover-timeout mymaster 5000
          sentinel parallel-syncs mymaster 3

          acllog-max-len 128
          sentinel deny-scripts-reconfig yes
          sentinel resolve-hostnames no
          sentinel announce-hostnames no
          EOF

    - name: Change Redis Sentinel Master Config File
      shell:
        cmd: |
          cat > /etc/systemd/system/redis.service.d/override.conf << EOF
          [Service]
          ReadWriteDirectories=/redis/redis_data
          ReadWriteDirectories=/redis/redis_log
          EOF    

    - name: Change Redis Sentinel Master Config File
      shell:
        cmd: |
          cat > /etc/systemd/system/sentinel.service.d/override.conf << EOF
          [Service]
          ReadWriteDirectories=/redis/redis_sentinel_data
          ReadWriteDirectories=/redis/redis_log
          EOF    
    
    - name: Restarting Redis-Server and Applying New Config
      shell: systemctl daemon-reload && systemctl restart redis-server

    - name: Restarting Redis-Sentinel and Applying New Config
      shell: systemctl daemon-reload && systemctl restart redis-sentinel

    - name: Change Redis-Server Log Rotate
      shell:
         cmd: |
            cat > /etc/logrotate.d/redis-server << EOF
            /redis/redis_log/*.log 
            {
              daily
              missingok
              copytruncate
              rotate 15
              maxage 15
              compress
              notifempty
            }
            EOF

    - name: Config Cronjob for Redis Log Cleanup
      cron:
        name: "Redis Log Cleaning"
        minute: "08"
        hour: "10"
        job: find /redis/redis_log/ -name "*.log" -type f -mtime +30 -exec rm -rf {} \;

    - name: Restarting Logrotate
      shell: systemctl restart logrotate